[project]
name = "ecomm-data-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "daft>=0.5.8",
    "duckdb>=1.3.1",
    "pandas>=2.3.0",
]
